[env:waveshare-esp32-s3-touch-amoled-1-8]
; Use pioarduino platform so the new IDF/Arduino APIs exist
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

; Match the Waveshare board specs (ESP32-S3R8, 16MB flash, 8MB PSRAM)
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
;board_build.partitions = partitions.csv

build_flags =
  -w
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM=1
  -DARDUINO_USB_MSC_ON_BOOT=0
  -mfix-esp32-psram-cache-issue
  -DXPOWERS_CHIP_AXP2101

lib_deps =
  lvgl/lvgl @ 8.3.11

upload_speed = 921600
monitor_speed = 115200
